### ISSUE TITLE
Feature request - delete message feature

### ISSUE THREAD

**Issue by akhilnarang** [ksdfg/neko-chan-telebot#33]
`/del`
First check if a message is quoted or not, else error.
Then, bot admin check
Then check if quoted message is user's own, else error if user is not admin
Then can delete if admin, or if its the user's own message

**Comment by ksdfg** [comment]
Should I add this as a command in the admin module? or make a new `delete` module and let that have purge and this?

**Comment by akhilnarang** [comment]
@ksdfg The latter seems better, since it won't be purely admin
